# Numpy Essential

## 1.Array

In [1]:
# create an array
import numpy as np
x = np.array([1,2,3,4])
print(x)
print(type(x))

# create an list
y=[1,2,3,4]
print(y)
print(type(y))

# check which is faster using %timeit function
%timeit [i**4 for i in range(1,10) ] # this is for list
%timeit np.arange(1,10)**4 # for array
# output shows arrays are much fater than list 

[1 2 3 4]
<class 'numpy.ndarray'>
[1, 2, 3, 4]
<class 'list'>
3.55 μs ± 225 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
1.94 μs ± 545 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [4]:
# convert a list into array
y =[1,2,3,4]
x=np.array(y)
print(type(x),type(y))

# craete an empty  list ,gets user input add to it and convert into array
l =[]
for i in range(1,5):
    num=int(input("Enter the element :"))
    l.append(num)
print(np.array(l))  

<class 'numpy.ndarray'> <class 'list'>


Enter the element : 1
Enter the element : 2
Enter the element : 5
Enter the element : 69


[ 1  2  5 69]


In [7]:
# create a 2D Array
x =np.array([[1,2,3],[8,9,10]])
print(x.ndim,x)# ndim used to know about dimension of array

# create a 3D Array
y =np.array([[[1,2,3],[5,6,9]]])
print(y.ndim,y)

# create a ndimensional array
z=np.array([1,2,3,4],ndmin=6)#here ndmin function used to give dimensions to particular array
print(z.ndim,z)

2 [[ 1  2  3]
 [ 8  9 10]]
3 [[[1 2 3]
  [5 6 9]]]
6 [[[[[[1 2 3 4]]]]]]


In [15]:
# special types of Array
# 1.zeros
ar_zero=np.zeros(4)
print(ar_zero)
ar =np.zeros((2,3))
print(ar)

#2. Ones
ar_ones =np.ones(5)
print(ar_ones)

#3.empty
ar_empty=np.empty(5)
print(ar_empty)

#4.Range
ar_range=np.arange(4)
print(ar_range)

# 5.diagonal
ar_diagonal=np.eye(3,3)
print(ar_diagonal)

# 6.linespace
ar_linespace=np.linspace(0,20,num=5)
print(ar_linespace)

[0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1.]
[0 1 2 3]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[ 0.  5. 10. 15. 20.]


## 2.Array with random numbers

* creating numpy array with random numbers
1. rand() : generate random values between 0 to 1
2. randn() : generate random values close to zero(positive or negative)
3. ranf() : generate random values in interval [0.0 ,1.0) ie. one is not included 
4. randint() : generate random numbers in given range  

In [17]:
import numpy as np

# 1.Rand()
var_1 =np.random.rand(2,3)
print(var_1)

# 2.Randn()
var_2 =np.random.randn(4)
print(var_2)

# 3.Ranf()
var_3 =np.random.ranf(5)
print(var_3)

# 4.randint()
var_4=np.random.randint(5,500,10,dtype=int)#here 5 is min value ,500 is maximun value and 10 is no of values
print(var_4)

[[0.24199167 0.37928763 0.98096119]
 [0.86175592 0.55792297 0.60708603]]
[ 1.04946654 -1.17290488  0.1691313  -0.52413221]
[0.22306189 0.70650332 0.91885916 0.27619929 0.46810167]
[391 138 253 364  12 421 311 497 119 235]


## 3.Datatypes in Numpy

In [21]:
# dtype()
var = np.array([1,2,3,4])
print('datatype :',var.dtype)

# convert one datatype into another 
x =np.array([1,2,3,4])
print(x.dtype,x)

y =np.array([1,2,3,4],dtype=np.int8)
print(y.dtype,y)

z =np.array([1,2,3,4],dtype="f")
print(z.dtype,z)

datatype : int64
int64 [1 2 3 4]
int8 [1 2 3 4]
float32 [1. 2. 3. 4.]


In [23]:
# Datatype as a Function
x =np.array([1,2,3,4])
new =np.float32(x)
print(x.dtype,new.dtype)

var = np.array(['a','b','c'])
var_1= np.array(['a','b','c',1,2,3])
print(var.dtype,var_1.dtype)

int64 float32
<U1 <U21


## 4.Shape and Reshaping of Array

In [25]:
# shape()
x =np.array([[1,2,3],[4,5,6]])
print(x.shape,x) # 2 rows 3 columns

var_1 = np.array([1,2,3,4],ndmin =4)
print(var_1.ndim,var_1.shape,var_1)
#here 3 one's are no of rows and 4 is no of column


(2, 3) [[1 2 3]
 [4 5 6]]
4 (1, 1, 1, 4) [[[[1 2 3 4]]]]


In [30]:
# Reshape()
# create a 1D array
x=np.array([1,2,3,4,6,7])
print(x.ndim,x)
y= x.reshape(2,3)
print(y.ndim,y)

# getting 2D array
x1=np.array([1,2,3,4,5,6,7,8,9])
print(x1.ndim,x1)
y1 = x1.reshape(3,3)
print(y1.ndim,y1) # 2D array

# getting  3D array
x3=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(x3.ndim,x3)

y3 = x3.reshape(2,3,2) # 3d array
print(y3.ndim,y3)

1 [1 2 3 4 6 7]
2 [[1 2 3]
 [4 6 7]]
1 [1 2 3 4 5 6 7 8 9]
2 [[1 2 3]
 [4 5 6]
 [7 8 9]]
1 [ 1  2  3  4  5  6  7  8  9 10 11 12]
3 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [31]:
# convert 3D array into 1D array
x3 =np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(x3.ndim,x3)

y3=x3.reshape(2,3,2)
print(y3.ndim,y3)

new_y =y3.reshape(-1)# -1 indicate the reverse change 
print(new_y,new_y.ndim)

1 [ 1  2  3  4  5  6  7  8  9 10 11 12]
3 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12] 1


## 5.Arithmetic Operation

In [32]:
# 1. Addition and Subtraction
var =np.array([1,2,3,4])
var_add = var +3
print(var_add)

var1 =np.array([1,2,3,4])
var2 =np.array([5,6,7,8])
var_add = var1 - var2
print(var_add)

# 2. Multiplication and Division
var = np.array([1,2,3,4])
var_mul = var*2
print(var_mul)

var_div =var/2
print(var_div)

var_mo =var%2
print(var_mo)

[4 5 6 7]
[-4 -4 -4 -4]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[1 0 1 0]


In [33]:
# arithematic operation using the numpy functions 
var1 =np.array([1,2,3,4])
var2 =np.array([5,6,7,8])

var_add = np.add(var1,var2)
print(var_add)

var_sub =np.subtract(var1,var2)
print(var_sub)


var_mul =np.multiply(var1,var2)
print(var_mul)

# reciprocal
var =np.array([1,2,3,4,5])
var_reciprocal=np.reciprocal(var)
print(var_reciprocal)

# 2d array
var1 =np.array([[1,2],[1,2]])
var2 =np.array([[1,3],[1,3]])

var_add =np.add(var1,var2)
print(var_add)
print(var_add.ndim)

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[1 0 0 0 0]
[[2 5]
 [2 5]]
2


## 6.Arithmetic Functions in Numpy

In [34]:
var =np.array([1,2,3,4,5])
print(np.min(var))
print("position min",np.argmin(var))
print(np.max(var))
print("position max",np.argmax(var))


# here axis =0 is for column and axis=1 is for row
var1=np.array([[1,2],[3,4]])
print(np.min(var1,axis=1))
print(np.min(var1,axis=0))

#square root
var =np.array([1,2,3,4,5])
print("square root :",np.sqrt(var))

# trignometry
x= np.array([1,2,3])
print(np.sin(x))
print(np.cos(x))
print(np.cumsum(x))

1
position min 0
5
position max 4
[1 3]
[1 2]
square root : [1.         1.41421356 1.73205081 2.         2.23606798]
[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[1 3 6]


## 7.Broadcasting in array

In [35]:
var1=np.array([1,2,3])
var2=np.array([[1],[2],[3]])

print(var1+var2)
print(var1)
print(var2)

[[2 3 4]
 [3 4 5]
 [4 5 6]]
[1 2 3]
[[1]
 [2]
 [3]]


## 8.Indexing in numpy array

In [36]:
# for 1D array
var = np.array([1,2,3,4])
print(var[2])
print(var[-3])

# for 2D array
var = np.array([[1,2,3,4],[12,5,9,3]]) 
print(var)
print(var.ndim)
print(var[1,2])

#for 3D array
var1 =np.array([[[1,2],[3,4]]])
print(var1)
print(var1.ndim)
print(var1[0,1,1])

3
2
[[ 1  2  3  4]
 [12  5  9  3]]
2
9
[[[1 2]
  [3 4]]]
3
4


## 9.Slicing in Numpy

In [37]:
# slicing in 1D array
var = np.array([1,2,3,4,5,6])
print(var)
print(var[1:5])
print(var[0:])
print(var[:5])

# stop point 
print(var[::2])
print(var[0:5:2])

# slicing in 2D array
var = np.array([[1,2,3,4],[5,6,7,9],[10,11,12,13]])
print(var)
print()
print('6 to 9',var[1,1:])

[1 2 3 4 5 6]
[2 3 4 5]
[1 2 3 4 5 6]
[1 2 3 4 5]
[1 3 5]
[1 3 5]
[[ 1  2  3  4]
 [ 5  6  7  9]
 [10 11 12 13]]

6 to 9 [6 7 9]


## 10.Iteration in numpy

In [39]:
# for 1D array
var = np.array([1,2,3,4,5,6])
print(var)
for i in var:
    print(i)

# for 2D array
var1 = np.array([[1,2,3,4],[5,6,7,8]])
print(var1)
print()
for i in var1:
    print(i)
print()
for i in var1:
    for j in i:
        print(j) 

# for 3D array
var2 = np.array([[[1,2,3],[4,5,6]]])
print(var2)

print()
print(var2.ndim)
print()
for i in var2:
    for j in i:
        for k in j:
            print(k)

[1 2 3 4 5 6]
1
2
3
4
5
6
[[1 2 3 4]
 [5 6 7 8]]

[1 2 3 4]
[5 6 7 8]

1
2
3
4
5
6
7
8


### 1.niterator function

In [40]:
var2 = np.array([[[1,2,3],[4,5,6]]])
print(var2)

print()
print(var2.ndim)
print()

for i in np.nditer(var2):
    print(i)

[[[1 2 3]
  [4 5 6]]]

3

1
2
3
4
5
6


In [41]:
## go to function 
np.nditer??

Init signature: np.nditer(self, /, *args, **kwargs)
Docstring:     
nditer(op, flags=None, op_flags=None, op_dtypes=None, order='K',
    casting='safe', op_axes=None, itershape=None, buffersize=0)

Efficient multi-dimensional iterator object to iterate over arrays.
To get started using this object, see the
:ref:`introductory guide to array iteration <arrays.nditer>`.

Parameters
----------
op : ndarray or sequence of array_like
    The array(s) to iterate over.

flags : sequence of str, optional
      Flags to control the behavior of the iterator.

      * ``buffered`` enables buffering when required.
      * ``c_index`` causes a C-order index to be tracked.
      * ``f_index`` causes a Fortran-order index to be tracked.
      * ``multi_index`` causes a multi-index, or a tuple of indices
        with one per iteration dimension, to be tracked.
      * ``common_dtype`` causes all the operands to be converted to
        a common data type, with copying or buffering as necessary.
      * 

In [42]:
var2 = np.array([[[1,2,3],[4,5,6]]])
print(var2)

print()
print(var2.ndim)
print()



#If var2 contains numbers or Unicode strings, they will be converted into byte strings during iteration.

for i in np.nditer(var2,flags=['buffered'],op_dtypes=['S']):#op_dtypes=['S'] is used, each element will be displayed as a byte string (e.g., b'Hello' instead of 'Hello').
    print(i)
    
    
# The buffered flag in np.nditer() allows NumPy to create a temporary copy (buffer) of the data when needed. This is useful in two main cases:

# Type Conversion: If you want to iterate over an array in a different data type than its original type (like converting numbers to strings), NumPy creates a temporary version of the data in the new format.

# Non-Contiguous Memory Layouts: In NumPy, some arrays are stored in a way that is not continuous in memory (like transposed matrices). Normally, iterating over such arrays can be inefficient, so NumPy creates a temporary, well-structured version of the data for smooth iteration.
# So, in simple terms, buffered helps make iteration smoother when direct access to the original data is tricky '''    

[[[1 2 3]
  [4 5 6]]]

3

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'4')
np.bytes_(b'5')
np.bytes_(b'6')


### 2.ndenumerate function

In [43]:
# it is used to iterate array with its index
var2 = np.array([[[1,2,3],[4,5,6]]])
print(var2)

print()
print(var2.ndim)
print()


for i in np.ndenumerate(var2):
    print(i)

[[[1 2 3]
  [4 5 6]]]

3

((0, 0, 0), np.int64(1))
((0, 0, 1), np.int64(2))
((0, 0, 2), np.int64(3))
((0, 1, 0), np.int64(4))
((0, 1, 1), np.int64(5))
((0, 1, 2), np.int64(6))


## 11.Copy and View

* difference between copy and view 
1. the copy owns data ,the view doesnt 
2. the copy of an array is new array ,the view of the original array
3. the changes made in copy doesnot affect the original one but view does

In [44]:
import numpy as np

var = np.array([1,2,3,4])

co =var.copy()
var[2]=22
print("var ",var)
print('copy',co)

var  [ 1  2 22  4]
copy [1 2 3 4]


In [45]:
var1 = np.array([1,2,3,4])

vi =var1.view()

var1[2]=22
print("var ",var1)
print('view',vi)

var  [ 1  2 22  4]
view [ 1  2 22  4]


## 12.Join and split function

In [46]:
#join = putting contents of two or more arrays in single array (dimension needed to be same )

# for 1D array
var = np.array([11,22,33,44])
var1 = np.array([1,2,3,4])

join = np.concatenate((var,var1))
print(join)

#for 2D array
# for two  dimensional array
var1 = np.array([[1,2,3,4],[5,6,7,8]])
var2 = np.array([[7,8,3,7],[5,6,76,81]])

join1 = np.concatenate((var1,var2),axis=0)
join2 = np.concatenate((var1,var2),axis=1)
print(var1)
print()
print(var2)
print()
print(join1)
print()
print(join2)

[11 22 33 44  1  2  3  4]
[[1 2 3 4]
 [5 6 7 8]]

[[ 7  8  3  7]
 [ 5  6 76 81]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 7  8  3  7]
 [ 5  6 76 81]]

[[ 1  2  3  4  7  8  3  7]
 [ 5  6  7  8  5  6 76 81]]


## 13.Stack Function

In [48]:
var = np.array([11,22,33,44])
var1 = np.array([1,2,3,4])


new_ar = np.stack((var,var1),axis =0)

new_ar1 = np.hstack((var,var1))# merze row wise

new_ar2 = np.vstack((var,var1))# merze column wise

new_ar3 = np.dstack((var,var1))# merze height wise


print(new_ar)
print()
print(new_ar1)
print()
print(new_ar2)
print()
print(new_ar3)


[[11 22 33 44]
 [ 1  2  3  4]]

[11 22 33 44  1  2  3  4]

[[11 22 33 44]
 [ 1  2  3  4]]

[[[11  1]
  [22  2]
  [33  3]
  [44  4]]]


In [49]:
# split the array

# for 1D array
var = np.array([11,22,33,44])
print(var)
print(type(var))
ar = np.array_split(var,2)# 2 refres to how many array we required
print(ar)
print(type(ar))

# to get array from that 
print(ar[0])


# for 2D array
var1 = np.array([[1,2,3,4],[5,6,7,8]])
print(var1)


ar = np.array_split(var1,5)
print()
print(ar)

[11 22 33 44]
<class 'numpy.ndarray'>
[array([11, 22]), array([33, 44])]
<class 'list'>
[11 22]
[[1 2 3 4]
 [5 6 7 8]]

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([], shape=(0, 4), dtype=int64), array([], shape=(0, 4), dtype=int64), array([], shape=(0, 4), dtype=int64)]


## 14.Search ,Sort ,Search Sorted ,Filter

In [51]:
# 1.Search :search for certain value,and return the indexes that get matched
var = np.array([1,2,3,4,56,7,89,2,23,5,4,2,9,4])

s =np.where(var == 2)
print(s)#in output it gives the index number  of a query

# 2.search sorted array: perform binary search in array and return the index where the specified value would be inserted to maintain the search order 
var = np.array([1,2,3,4,5,6,7,8])
var1 = np.array([1,2,3,4,7,8])



s =np.searchsorted(var,5)
v =np.searchsorted(var,6,side="right")
p =np.searchsorted(var1,[5,6,7],side="left")
print(s)
print(v)
print(p)

#3.sort array : ordered sequence in any sequence that has an ordered  corresponding elements like numeric or alphabetical
var = np.array([1,2,4,5,6,7,3,8])
x = np.sort((var))
print(x)

#4.filter array : getting some elements out of an existing array and creating a new array out of them 
var = np.array([2,5,6,89,2,5,7])

x=[True,True,True,False,True,False,True]

new_ar = var[x] 
print(new_ar)

(array([ 1,  7, 11]),)
4
6
[4 4 4]
[1 2 3 4 5 6 7 8]
[2 5 6 2 7]


## 15.Special Function in Numpy

In [52]:
import numpy as np

# shuffle function
var = np.array([2,5,6,89,2,5,7])

np.random.shuffle(var)

print(var)

[ 2  5  7  2  6 89  5]


In [53]:
# unique function
var = np.array([2,5,6,89,2,5,7])

x= np.unique(var,return_index=True,return_counts=True )

print(x)

(array([ 2,  5,  6,  7, 89]), array([0, 1, 2, 6, 3]), array([2, 2, 1, 1, 1]))


In [54]:
# resize function
var = np.array([2,5,6,89,2,5,7])

x =np.resize(var,(3,3))
print(x)

[[ 2  5  6]
 [89  2  5]
 [ 7  2  5]]


In [56]:
# flatten and ravel
var = np.array([[2,5,6,89,2],[2,6,9,8,22]])

print("flatten",var.flatten(order="F"))
print("ravel",np.ravel(var,order="K"))

flatten [ 2  2  5  6  6  9 89  8  2 22]
ravel [ 2  5  6 89  2  2  6  9  8 22]


## 16.insert and delete function

In [59]:
# insert :it does not  accept float value,it accepts an integer value
var = np.array([1,2,3,45,6])
print(var)

v= np.insert(var,(2,3,4),44)
print(v)

# for 2D array
var1 =np.array([[1,2,3,4],[5,6,7,80]])

v1 =np.insert(var1,2,22,axis=0)

# for multiple data insert 

v2 =np.insert(var1,2,[22,12,13,14],axis=0)

print(v1)
print(v2)

[ 1  2  3 45  6]
[ 1  2 44  3 44 45 44  6]
[[ 1  2  3  4]
 [ 5  6  7 80]
 [22 22 22 22]]
[[ 1  2  3  4]
 [ 5  6  7 80]
 [22 12 13 14]]


In [60]:
#append function 
var = np.array([1,2,3,45,6])

x=np.append(var,0.5)

print(x)

var1 =np.array([[1,2,3,4],[5,6,7,80]])

y = np.append(var1,[[45,44,23,5]],axis=0)

print(y)

var = np.array([1,2,3,45,6])
print(var)

v = np.delete(var,2)
print(v)

[ 1.   2.   3.  45.   6.   0.5]
[[ 1  2  3  4]
 [ 5  6  7 80]
 [45 44 23  5]]
[ 1  2  3 45  6]
[ 1  2 45  6]


## 17.Matrix

In [61]:
var = np.matrix([[1,2,3],[4,5,6]])
print(var)
print(type(var))

[[1 2 3]
 [4 5 6]]
<class 'numpy.matrix'>


In [62]:
var = np.matrix([[1,2],[4,5]])
var1 = np.matrix([[2,3],[4,6]])

print(var*var1)

print(var.dot(var1)) # dot calculation means simple matrix multiplication 

[[10 15]
 [28 42]]
[[10 15]
 [28 42]]


### Matrix function

1. Transpose 
2. swapaxes
3. inverse 
4. power
5. determinant

In [63]:
# transpose 
var = np.matrix([[1,2,3],[4,5,6]])
print(np.transpose(var))
# or 
print(var.T)

[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


In [64]:
# Swapaxes 
var = np.matrix([[1,2,3],[4,5,6]])
print(np.swapaxes(var,0,1))

[[1 4]
 [2 5]
 [3 6]]


In [65]:
# inverse matrix 
var = np.matrix([[1,2],[4,5]])
print(np.linalg.inv(var))

[[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]


In [66]:
# power
var = np.matrix([[1,2],[4,6]])
print(np.linalg.matrix_power(var,3))

[[ 65 102]
 [204 320]]


In [67]:
# determinant matrix 
var = np.matrix([[1,2],[4,6]])
print(np.linalg.det(var))

-2.0
